resources:
- repo: self
pool:
  vmImage: 'vs2017-win2016'
steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: ./
    filePath: build.ps1
    arguments: '--env=wac --pack --version=0.1.$(Build.BuildNumber)'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '$(Build.SourcesDirectory)/**/*.nupkg;!$(Build.SourcesDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'IIS-WAC-MyGet'

