resources:
- repo: self

pool:
  name: IISAdministration

steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: ./
    filePath: build.ps1
    arguments: '--env=wac --pack --version=0.1.$(Build.BuildNumber)'

